/**
 * Vajra Aegis - GitHub Actions Integration
 * 
 * Generate GitHub Actions workflows for security scanning
 * Features:
 * - Aegis scan workflow
 * - PR comments
 * - Status checks
 * - Auto-fix PRs
 */

export interface WorkflowConfig {
    name: string;
    triggers: ('push' | 'pull_request' | 'schedule')[];
    branches: string[];
    scanMode: 'quick' | 'full' | 'deep';
    failOn: ('critical' | 'high' | 'medium')[];
    prComment: boolean;
    sarif: boolean;
    autoFix: boolean;
    schedule?: string;
}

/**
 * Generate Aegis GitHub Actions workflow
 */
export function generateWorkflow(config: Partial<WorkflowConfig> = {}): string {
    const fullConfig: WorkflowConfig = {
        name: 'Vajra AEGIS Security Scan',
        triggers: ['push', 'pull_request'],
        branches: ['main', 'develop'],
        scanMode: 'full',
        failOn: ['critical', 'high'],
        prComment: true,
        sarif: true,
        autoFix: false,
        ...config,
    };

    const workflow = `# Vajra AEGIS Security Scan
# Generated by Vajra Security Platform
# https://github.com/shikhar1809/Vajra

name: ${fullConfig.name}

on:
${generateTriggers(fullConfig)}

permissions:
  contents: read
  security-events: write
  pull-requests: write
  issues: write

env:
  VAJRA_API_KEY: \${{ secrets.VAJRA_API_KEY }}

jobs:
  security-scan:
    name: Security Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better analysis

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📥 Install dependencies
        run: npm ci --ignore-scripts

      - name: 🔍 Run Vajra AEGIS Scan
        id: aegis-scan
        run: |
          # Run the Aegis security scan
          npx vajra-aegis scan \\
            --mode ${fullConfig.scanMode} \\
            --output json \\
            --output-file aegis-results.json \\
            ${fullConfig.sarif ? '--sarif sarif-results.sarif' : ''} \\
            --fail-on ${fullConfig.failOn.join(',')} || echo "SCAN_FAILED=true" >> $GITHUB_ENV
          
          # Parse results for summary
          if [ -f aegis-results.json ]; then
            echo "CRITICAL=\$(jq '.summary.critical' aegis-results.json)" >> $GITHUB_OUTPUT
            echo "HIGH=\$(jq '.summary.high' aegis-results.json)" >> $GITHUB_OUTPUT
            echo "MEDIUM=\$(jq '.summary.medium' aegis-results.json)" >> $GITHUB_OUTPUT
            echo "LOW=\$(jq '.summary.low' aegis-results.json)" >> $GITHUB_OUTPUT
            echo "SCORE=\$(jq '.securityScore' aegis-results.json)" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

${fullConfig.sarif ? `
      - name: 📊 Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: sarif-results.sarif
        continue-on-error: true
` : ''}

${fullConfig.prComment ? `
      - name: 💬 Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            let results = { summary: { critical: 0, high: 0, medium: 0, low: 0 }, securityScore: 100 };
            try {
              results = JSON.parse(fs.readFileSync('aegis-results.json', 'utf8'));
            } catch (e) {
              console.log('Could not read results file');
            }
            
            const emoji = results.securityScore >= 80 ? '✅' : results.securityScore >= 60 ? '⚠️' : '🚨';
            const grade = results.securityScore >= 90 ? 'A' : results.securityScore >= 80 ? 'B' : 
                          results.securityScore >= 70 ? 'C' : results.securityScore >= 60 ? 'D' : 'F';
            
            const body = \`## \${emoji} Vajra AEGIS Security Report
            
### Security Score: \${results.securityScore}/100 (Grade: \${grade})

| Severity | Count |
|----------|-------|
| 🔴 Critical | \${results.summary.critical} |
| 🟠 High | \${results.summary.high} |
| 🟡 Medium | \${results.summary.medium} |
| 🟢 Low | \${results.summary.low} |

\${results.summary.critical > 0 || results.summary.high > 0 ? 
  '⚠️ **Action Required**: Please address critical and high severity issues before merging.' : 
  '✅ **No blocking issues found**. This PR is ready for review.'}

<details>
<summary>View detailed findings</summary>

See the Security tab for full SARIF results.

</details>

---
<sub>🛡️ Powered by [Vajra Security Platform](https://github.com/shikhar1809/Vajra)</sub>\`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });
` : ''}

      - name: 📋 Upload scan artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: aegis-security-report
          path: |
            aegis-results.json
            sarif-results.sarif
          retention-days: 30

      - name: 🚫 Fail on security issues
        if: env.SCAN_FAILED == 'true'
        run: |
          echo "❌ Security scan found issues that fail the build."
          echo "Please review the security report and fix the issues."
          exit 1

${fullConfig.autoFix ? `
  auto-fix:
    name: Auto-Fix Vulnerabilities
    runs-on: ubuntu-latest
    needs: security-scan
    if: failure() && github.event_name == 'pull_request'
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          ref: \${{ github.head_ref }}
          token: \${{ secrets.GITHUB_TOKEN }}
      
      - name: 🔧 Apply auto-fixes
        run: |
          npx vajra-aegis fix --auto
      
      - name: 📝 Commit fixes
        run: |
          git config user.name "Vajra Security Bot"
          git config user.email "security@vajra.app"
          git add -A
          git diff --staged --quiet || git commit -m "🔒 Security: Apply Vajra AEGIS auto-fixes"
          git push
` : ''}
`;

    return workflow;
}

function generateTriggers(config: WorkflowConfig): string {
    const triggers: string[] = [];

    if (config.triggers.includes('push')) {
        triggers.push(`  push:
    branches: [${config.branches.map(b => `'${b}'`).join(', ')}]`);
    }

    if (config.triggers.includes('pull_request')) {
        triggers.push(`  pull_request:
    branches: [${config.branches.map(b => `'${b}'`).join(', ')}]`);
    }

    if (config.triggers.includes('schedule') && config.schedule) {
        triggers.push(`  schedule:
    - cron: '${config.schedule}'`);
    }

    return triggers.join('\n');
}

/**
 * Generate pre-commit hook configuration
 */
export function generatePreCommitConfig(): string {
    return `# Vajra AEGIS Pre-commit Configuration
# Add to .pre-commit-config.yaml

repos:
  - repo: local
    hooks:
      - id: vajra-aegis-scan
        name: Vajra Security Scan
        entry: npx vajra-aegis scan --mode quick --fail-on critical
        language: system
        pass_filenames: false
        stages: [commit]
        
      - id: vajra-secrets-scan
        name: Vajra Secret Detection
        entry: npx vajra-aegis scan --secrets-only --fail-on critical
        language: system
        pass_filenames: false
        stages: [commit]
`;
}

/**
 * Generate CLI wrapper script
 */
export function generateCLI(): string {
    return `#!/usr/bin/env node
/**
 * Vajra AEGIS CLI
 * Command-line interface for security scanning
 */

const { createScanner } = require('./code-scanner');
const fs = require('fs');

async function main() {
  const args = process.argv.slice(2);
  const command = args[0];
  
  if (command === 'scan') {
    const options = parseArgs(args.slice(1));
    
    console.log('🔍 Starting Vajra AEGIS security scan...');
    const scanner = createScanner(process.cwd());
    
    const results = await scanner.scan({
      scanType: options.mode || 'full',
      aiEnhanced: options.ai !== 'false',
    });
    
    // Output results
    if (options.output === 'json' && options.outputFile) {
      fs.writeFileSync(options.outputFile, JSON.stringify(results, null, 2));
      console.log('📄 Results written to', options.outputFile);
    }
    
    // Generate SARIF if requested
    if (options.sarif) {
      const sarif = generateSARIF(results);
      fs.writeFileSync(options.sarif, JSON.stringify(sarif, null, 2));
      console.log('📊 SARIF written to', options.sarif);
    }
    
    // Display summary
    console.log('\\n📊 Security Scan Summary');
    console.log('========================');
    console.log(\`Security Score: \${results.securityScore}/100\`);
    console.log(\`Critical: \${results.summary.critical}\`);
    console.log(\`High: \${results.summary.high}\`);
    console.log(\`Medium: \${results.summary.medium}\`);
    console.log(\`Low: \${results.summary.low}\`);
    
    // Check fail conditions
    const failOn = (options.failOn || 'critical,high').split(',');
    let shouldFail = false;
    
    if (failOn.includes('critical') && results.summary.critical > 0) shouldFail = true;
    if (failOn.includes('high') && results.summary.high > 0) shouldFail = true;
    if (failOn.includes('medium') && results.summary.medium > 0) shouldFail = true;
    
    if (shouldFail) {
      console.log('\\n❌ Scan failed due to security issues');
      process.exit(1);
    } else {
      console.log('\\n✅ Scan passed');
    }
    
  } else if (command === 'fix') {
    console.log('🔧 Auto-fix not yet implemented');
    
  } else {
    console.log('Vajra AEGIS Security Scanner');
    console.log('Usage: vajra-aegis <command> [options]');
    console.log('');
    console.log('Commands:');
    console.log('  scan     Run security scan');
    console.log('  fix      Apply auto-fixes');
    console.log('');
    console.log('Options:');
    console.log('  --mode <quick|full|deep>    Scan mode');
    console.log('  --output <json>             Output format');
    console.log('  --output-file <path>        Output file path');
    console.log('  --sarif <path>              Generate SARIF output');
    console.log('  --fail-on <severities>      Fail on severities (comma-separated)');
    console.log('  --ai <true|false>           Enable AI analysis');
  }
}

function parseArgs(args) {
  const options = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith('--')) {
      const key = args[i].substring(2).replace(/-/g, '');
      options[key] = args[i + 1] || true;
      i++;
    }
  }
  return options;
}

function generateSARIF(results) {
  return {
    "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
    "version": "2.1.0",
    "runs": [{
      "tool": {
        "driver": {
          "name": "Vajra AEGIS",
          "version": "1.0.0",
          "informationUri": "https://github.com/shikhar1809/Vajra"
        }
      },
      "results": results.vulnerabilities.map(v => ({
        "ruleId": v.type,
        "level": v.severity === 'critical' ? 'error' : v.severity === 'high' ? 'warning' : 'note',
        "message": { "text": v.description },
        "locations": [{
          "physicalLocation": {
            "artifactLocation": { "uri": v.location.file },
            "region": { "startLine": v.location.startLine }
          }
        }]
      }))
    }]
  };
}

main().catch(console.error);
`;
}

// Export workflow files structure
export function getWorkflowFiles(config?: Partial<WorkflowConfig>): Record<string, string> {
    return {
        '.github/workflows/aegis-security.yml': generateWorkflow(config),
        '.pre-commit-config.yaml': generatePreCommitConfig(),
    };
}
